In [53]:
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
def to_float(lis):
    return float(lis)
a=datasets.load_digits()
#print(a)
#print(pd.Series(a.target))
y=pd.DataFrame(a.target)
print(a.data)
X=pd.DataFrame(a.data)
#print(X)
X_train,X_val,train_y,val_y=train_test_split(X,y,random_state=1)#划分测试集和
knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train,train_y)
prediction=knn_reg.predict(X_val)
print(len(prediction))
pre=[]
#print((val_y))
for i in prediction:
    pre.append(i[0])
#print(pre)
val=(list(val_y[0]))
#print(map(to_float,val))
m=pd.DataFrame({'prediction':list(pre),'val':list(map(to_float,val))})
print(m)
knn_reg.score(X_val,val_y)##计算准确率

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
450
     prediction  val
0           1.0  1.0
1           5.0  5.0
2           0.0  0.0
3           7.0  7.0
4           1.0  1.0
5           0.0  0.0
6           6.0  6.0
7           1.0  1.0
8           5.0  5.0
9           4.0  4.0
10          9.0  9.0
11          2.0  2.0
12          7.0  7.0
13          8.0  8.0
14          4.0  4.0
15          6.0  6.0
16          9.0  9.0
17          3.0  3.0
18          7.0  7.0
19          4.0  4.0
20          7.0  7.0
21          1.0  1.0
22          8.0  8.0
23          6.0  6.0
24          0.0  0.0
25          9.0  9.0
26          6.0  6.0
27          1.0  1.0
28          3.0  3.0
29          7.0  7.0
..          ...  ...
420         5.0  5.0
421         4.0  4.0
422         9.0  9.0
423         0.0  0.0
424         5.0  5.0
425         9.0  9.0
426   

0.9850879167458381

In [28]:
m

prediction  val
0        [1.0]  0.0
1        [5.0]  NaN
2        [0.0]  NaN
3        [7.0]  3.0
4        [1.0]  NaN
5        [0.0]  NaN
6        [6.0]  NaN
7        [1.0]  NaN
8        [5.0]  8.0
9        [4.0]  NaN
10       [9.0]  NaN
11       [2.0]  NaN
12       [7.0]  NaN
13       [8.0]  NaN
14       [4.0]  NaN
15       [6.0]  NaN
16       [9.0]  NaN
17       [3.0]  NaN
18       [7.0]  NaN
19       [4.0]  9.0
20       [7.0]  NaN
21       [1.0]  NaN
22       [8.0]  2.0
23       [6.0]  NaN
24       [0.0]  NaN
25       [9.0]  NaN
26       [6.0]  NaN
27       [1.0]  NaN
28       [3.0]  NaN
29       [7.0]  NaN
..         ...  ...
420      [5.0]  NaN
421      [4.0]  5.0
422      [9.0]  NaN
423      [0.0]  NaN
424      [5.0]  8.0
425      [9.0]  NaN
426      [1.0]  NaN
427      [4.0]  NaN
428      [5.0]  1.0
429      [0.0]  NaN
430      [4.0]  NaN
431      [3.0]  NaN
432      [4.0]  5.0
433      [2.0]  NaN
434      [4.0]  0.0
435      [9.0]  0.0
436      [0.0]  NaN
437      [8.0]  NaN
438      [7.0]  NaN
439      [8.0]  NaN
440      [6.0]  NaN
441      [9.0]  NaN
442      [4.0]  1.0
443      [5.0]  NaN
444      [7.0]  NaN
445      [8.0]  NaN
446      [3.0]  3.0
447      [7.0]  7.0
448      [8.0]  NaN
449      [3.0]  NaN

[450 rows x 2 columns]

In [73]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_digits
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt

iris = load_iris()
x_data = iris.data
y_data = iris.target

def zeroMean(dataMat):
    meanVal = np.mean(dataMat, axis= 0)
    newData = dataMat - meanVal
    return newData, meanVal

def PCA(dataMat, top):
    #数据中心化
    newData, meanVal = zeroMean(dataMat)
    #cov用于求协方差矩阵，参数rowvar = 0说明数据一行代表一个样本
    covMat = np.cov(newData, rowvar=0)
    #np.linalg.eig用于求矩阵的特征值和特征向量
    eigVals, eigVects = np.linalg.eig(np.mat(covMat))
    #对特征值从小到大排列
    eigValIndice = np.argsort(eigVals)
    #得到最大的n个特征值的下标
    n_eigValIndice = eigValIndice[-1:-(top + 1): -1]
    #得到下标对应的特征向量
    n_eigVects = eigVects[:, n_eigValIndice]
    #低维特征空间的数据
    lowDDataMat = newData * n_eigVects
    # print(newData)
    print(n_eigVects)
    # print(lowDDataMat)
    #利用低维度数据来重构数据
    reconMat = (lowDDataMat * n_eigVects.T) + meanVal
    return lowDDataMat, reconMat


#将数据降至2维
lowDDataMat, reconMat = PCA(x_data, 2)


x = np.array(lowDDataMat)[:, 0]
y = np.array(lowDDataMat)[:, 1]
plt.scatter(x, y, c = y_data)
plt.show()

[[ 0.36158968 -0.65653988]
 [-0.08226889 -0.72971237]
 [ 0.85657211  0.1757674 ]
 [ 0.35884393  0.07470647]]


<Figure size 640x480 with 1 Axes>